server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/gighaven
    username: kamal
    password: password
    #driver-class-name:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      password: jjjj

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000