server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gighaven
    username: kamal
    password: password
    #driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      password: jjjj

jwt:
  secret-key: JWTSuperSecretKeyffffffffffffffffffffffffffffffffff
  expiration: 604800000
  refresh-token:
    expiration: 604800000

gighaven:
  message_room:
    page_size: 500